---
title: "Accidents de la route caractéristiques"
author: "Valentin Henriot"
date: "5/16/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE}
library(readr)
library(dplyr)
library(tidyr)
library(ggplot2)
```

```{r message=FALSE}
AccidentCarac <- read_csv("https://www.data.gouv.fr/fr/datasets/r/6eee0852-cbd7-447e-bd70-37c433029405")
```

```{r}
AccidentCarac$lum <- as.factor(AccidentCarac$lum)
AccidentCarac$agg <- as.factor(AccidentCarac$agg)
AccidentCarac$int <- as.factor(AccidentCarac$int)
AccidentCarac$atm <- as.factor(AccidentCarac$atm)
AccidentCarac$col <- as.factor(AccidentCarac$col)

AccidentCarac$lum <- recode(AccidentCarac$lum, "1" = "Plein jour", "2" = "Crépuscule ou aube", "3" = "Nuit sans éclairage public", "4" = "Nuit avec éclairage public non allumé", "5" = "Nuit avec éclairage public allumé")

AccidentCarac$agg <- recode(AccidentCarac$agg, "1" = "Hors agglo", "2" = "Agglo")

AccidentCarac$int <- recode(AccidentCarac$int, "1" = "Hors intersection", "2" = "Intersection en X", "3" = "Intersection en T", "4" ="Intersection en Y", "5" = "Intersection plus de 4 branches", "6" = "Giratoire", "7" = "Place", "8" = "Passage à niveau", "9" = "Autre intersection")

AccidentCarac$atm <- recode(AccidentCarac$atm, "1" = "Normale", "2" = "Pluie légère", "3" = "Pluie forte", "4" = "Neige / Grêle", "5" = "Brouillard / Fumée", "6" = "Vent fort / Tempête", "7" = "Temps éblouissant", "8" = "Temps couvert", "9" = "Autre")

AccidentCarac$col <- recode(AccidentCarac$col, "1" = "Deux VL - frontale", "2" = "Deux VL - par l'arrière", "3" = "Deux VL - par le côté", "4" = "Trois VL ou plus - en chaîne", "5" = "Trois VL ou plus - collisions multiples", "6" = "Autre collison", "7" = "Sans collision")
```

```{r message=FALSE}
AccidentUsager <- read_csv("https://www.data.gouv.fr/fr/datasets/r/72b251e1-d5e1-4c46-a1c2-c65f1b26549a")
```

```{r}
AccidentJoin <- left_join(AccidentCarac, AccidentUsager, by = "Num_Acc")
```

```{r}
AccidentJoin$an <- AccidentJoin$an+2000
AccidentJoin$age <- AccidentJoin$an - AccidentJoin$an_nais
```

```{r include=FALSE}
AccidentJoin$date <- paste(AccidentJoin$an, AccidentJoin$mois, AccidentJoin$jour, sep = "/")

AccidentJoin$date <-  as.Date(AccidentJoin$date)
```

```{r}
AccidentJoin[order(AccidentJoin$date),]
```

```{r}
AccidentJoin$place <- as.factor(AccidentJoin$place)
AccidentJoin$catu <- as.factor(AccidentJoin$catu)
AccidentJoin$grav <- as.factor(AccidentJoin$grav)
AccidentJoin$sexe <- as.factor(AccidentJoin$sexe)
AccidentJoin$trajet <- as.factor(AccidentJoin$trajet)
AccidentJoin$secu <- as.factor(AccidentJoin$secu)
AccidentJoin$locp <- as.factor(AccidentJoin$locp)
AccidentJoin$actp <- as.factor(AccidentJoin$actp)
AccidentJoin$etatp <- as.factor(AccidentJoin$etatp)

AccidentJoin$place <- recode(AccidentJoin$place, "1" = "Conducteur", "2" = "Passager avant", "6" = "Passager AVM", "7" = "Passager ARG", "8" = "Passager ARM", "9" = "Passager ARD", "3" = "Passager ARD", "4" = "Passager ARG", "5" = "Passager ARM")

AccidentJoin$catu <- recode(AccidentJoin$catu, "1" = "Conducteur",
"2" = "Passager",
"3" = "Piéton",
"4" = "Piéton en roller ou en trottinette")

AccidentJoin$grav <- recode(AccidentJoin$grav, "1" = "Indemne", "2" = "Tué", "3" = "Grave", "4" = "Léger")

AccidentJoin$sexe <- recode(AccidentJoin$sexe, "1" = "Homme", "2" = "Femme")

AccidentJoin$trajet <- recode(AccidentJoin$trajet, "1" = "Domicile – travail",
"2" = "Domicile – école",
"3" = "Courses – achats",
"4" = "Utilisation professionnelle",
"5" = "Promenade – loisirs",
"9" = "Autre")

AccidentJoin$secu <- recode(AccidentJoin$secu, "11" = "Ceinture - Oui", "12" = "Ceinture - Non", "13" = "Ceinture - Non déterminable", "21" = "Casque - Oui", "22" = "Casque - Non", "23" = "Casque - Non déterminable")
```

```{r}
AccidentJoin$Classe_Age <- cut(AccidentJoin$age, c(0, 18, 26, 41, 61, 81, 100))
```

```{r}
AccidentVehicule <- read_csv("https://www.data.gouv.fr/fr/datasets/r/b4aaeede-1a80-4d76-8f97-543dad479167")
```

```{r}
AccidentJoin2 <- left_join(AccidentJoin, AccidentVehicule, by = c("Num_Acc", "num_veh"))
```

```{r}
AccidentJoin2[order(AccidentJoin2$date),]
```

```{r}
AccidentJoin2$catv <- as.factor(AccidentJoin2$catv)

AccidentJoin2$catv <- recode(AccidentJoin2$catv, "01" = "Bicyclette", "02" = "Cyclomoteur<=50cm3", "03" = "Voiturette", "07" = "Voiture", "10" = "Véhicule utilitaire", "13" = "PL<7,5T", "14" = "PL>7,5T", "15" = "PL > 3,5T + remorque", "16" = "Tracteur", "17" = "Tracteur + remorque", "20" = "Engin spécial", "21" = "Tracteur agricole", "30" = "Scooter<=50cm3", "31" = "Motocyclette<=125cm3", "32" = "Scooter<=125cm3", "33" = "Moto>125cm3", "34" = "Scooter>125cm3", "35" = "Quad<=50cm3", "36" = "Quad>50cm3", "37" = "Bus", "38" = "Car", "39" = "Train", "40" = "Tramway", "99" = "Autre véhicule")
```

```{r}
AccidentJoin2$long <- as.numeric(AccidentJoin2$long)
```

```{r}
AccidentJoin2$lat <- AccidentJoin2$lat/100000
AccidentJoin2$long <- AccidentJoin2$long/100000
```

```{r}
write.csv2(AccidentJoin2, file = "ACCR2018.csv")
```

