---
title: "Test scrapping"
author: "Valentin Henriot"
date: "6/4/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
```

```{r}
library(stringr)
library(rvest)
library(htmltab)
library(tidyverse)
library(rlist)
library(stringi)
library(WikipediR)
library(ggplot2)
library(reshape2)
library(DataCombine)
```

# Test avec le package rvest

```{r}
url = "https://fr.wikipedia.org/wiki/Parc_automobile_français"
```

```{r}
sample = url %>%
  read_html() %>%
  html_node(xpath = '//*[@id="mw-content-text"]/div/table[1]') %>%
  html_table(fill = TRUE)
```

```{r}
print(paste('Les données du parc auto français contiennent', nrow(sample), 'lignes et', ncol(sample), 'colonnes'))
```

```{r}
sample2 = url %>%
  read_html() %>%
  html_node(xpath = '//*[@id="mw-content-text"]/div/table[2]') %>%
  html_table(fill = TRUE)
```

```{r}
sample3 = url %>%
  read_html() %>%
  html_node(xpath = '//*[@id="mw-content-text"]/div/table[3]') %>%
  html_table(fill = TRUE)
```

# Scrapping ZePerf (à mettre sur un autre doc .rmd)

## À SUPPRIMER (transféré sur autre document)

```{r}
urlzp = read_html("http://www.zeperfs.com/fiche1583-bmw-120-d.htm")
```

```{r}
TestZP <- urlzp %>%
  html_node('table') %>%
  html_table()
```

```{r}
TestZP2 <- TestZP[,-3] 
TestZP3 <- TestZP2[-2:-5,]
```

```{r}
TestZP3$X2 <- gsub("@zeperfs.com", "", TestZP3$X2)
TestZP3$X2 <- gsub("km/h", "", TestZP3$X2)
TestZP3$X2 <- gsub("m.", "", TestZP3$X2)
TestZP3$X2 <- gsub("s.", "", TestZP3$X2)
```

```{r}
BMW120DT1 <- TestZP3 %>% 
  separate_rows(X1, sep = ":")

BMW120DT1 <- BMW120DT1[-49,]
BMW120DT1 <- BMW120DT1[,-2]

BMW120DT1 <- as.data.frame(BMW120DT1)
```

```{r}
BMW120DT2 <- TestZP3 %>% 
  separate_rows(X2, sep = " ")

BMW120DT2 <- BMW120DT2[,-1]

BMW120DT2 <- gsub(pattern = "\\s",   
     replacement = "",
     x = BMW120DT2) ## Pour supprimer tous les espaces

BMW120DT2[BMW120DT2 == "" ] <- NA ## Remplacer les cellules vides par des NA

is.na(BMW120DT2) ## Test pour voir le nombre de valeurs manquantes

BMW120DT2 <- na.omit(BMW120DT2) ## Suppression valeurs manquantes

BMW120DT2 <- as.data.frame(BMW120DT2)

BMW120DT2 <- BMW120DT2[-49:-60,]
```

```{r}
BMW120D <- cbind(BMW120DT1, BMW120DT2)
```

# Test avec le package WikipediR

```{r}
pages_sexualite= pages_in_category("fr",
                                      "wikipedia",
                                      categories="Sexualité humaine", 
                                      clean_response=TRUE)
print(data.frame(pages_sexualite$title))
```

```{r}
data=data.frame(title=pages_sexualite$title,
                longueur_pages=rep(NA,nrow(pages_sexualite)),
                nb_pages_vers=NA,
                nb_pages_depuis=NA,
                stringsAsFactors=FALSE)
for (i in 1:nrow(data)){
  info=page_info("fr",
                 "wikipedia",
                 page=data$title[i])
  data$longueur_pages[i]=info$query$pages[[1]][["length"]]
  mybacklinks=page_backlinks("fr",
                             "wikipedia",
                             page=data$title[i],
                             limit=500,
                             clean_response=TRUE)
    data$nb_pages_depuis[i]=length(mybacklinks)
    mylinks=page_links("fr",
                       "wikipedia",
                       page=data$title[i],
                       limit=500,
                       clean_response=TRUE)[[1]]$links
    data$nb_pages_vers[i]=length(mylinks)
}

data=arrange(data,desc(longueur_pages)) %>% mutate(ID=length(title):1)
print(head(data))
```

