---
title: "ZePerf Scrapping"
author: "Valentin Henriot"
date: "6/6/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
```

```{r}
library(stringr)
library(rvest)
library(htmltab)
library(tidyverse)
library(rlist)
library(stringi)
library(ggplot2)
library(reshape2)
library(DataCombine)
```

# Script de base à améliorer

```{r}
urlzp = read_html("http://www.zeperfs.com/fiche1583-bmw-120-d.htm") ## Appeler l'URL avec les données du véhicule souhaité
```

```{r}
TestZP <- urlzp %>%
  html_node('table') %>%
  html_table() ## Commande de scrapping
```

```{r}
TestZP2 <- TestZP[,-3] 
TestZP3 <- TestZP2[-2:-5,] ## Supprimer les données inutiles générées
```

```{r}
TestZP3$X2 <- gsub("@zeperfs.com", "", TestZP3$X2)
TestZP3$X2 <- gsub("km/h", "", TestZP3$X2)
TestZP3$X2 <- gsub("m.", "", TestZP3$X2)
TestZP3$X2 <- gsub("s.", "", TestZP3$X2)
```

```{r}
BMW120DT1 <- TestZP3 %>% 
  separate_rows(X1, sep = ":") ## Séparer les données pour avoir une donnée par ligne

BMW120DT1 <- BMW120DT1[-49,]
BMW120DT1 <- BMW120DT1[,-2]

BMW120DT1 <- as.data.frame(BMW120DT1)
```

```{r}
BMW120DT2 <- TestZP3 %>% 
  separate_rows(X2, sep = " ") ## Séparer les données pour avoir une donnée par ligne

BMW120DT2 <- BMW120DT2[,-1]

BMW120DT2 <- gsub(pattern = "\\s",   
     replacement = "",
     x = BMW120DT2) ## Pour supprimer tous les espaces

BMW120DT2[BMW120DT2 == "" ] <- NA ## Remplacer les cellules vides par des NA

is.na(BMW120DT2) ## Test pour voir le nombre de valeurs manquantes

BMW120DT2 <- na.omit(BMW120DT2) ## Suppression valeurs manquantes

BMW120DT2 <- as.data.frame(BMW120DT2)

BMW120DT2 <- BMW120DT2[-49:-60,]
```

```{r}
BMW120D <- cbind(BMW120DT1, BMW120DT2)
```

```{r}
BMW120D$BMW120DT1 <- as.character(BMW120D$BMW120DT1)

BMW120D$BMW120DT2 <- gsub("Ƽ", "5", BMW120D$BMW120DT2) ## Changer les Ƽ reconnus comme 'characters'
BMW120D$BMW120DT2 <- gsub("З", "3", BMW120D$BMW120DT2) ## Idem manip précédente

BMW120D$BMW120DT2 <- as.numeric(gsub("‚", ".", BMW120D$BMW120DT2, fixed = TRUE))
```

```{r}
base::colnames(BMW120D)[colnames(BMW120D)=="BMW120DT1"] <- "Catégories"
base::colnames(BMW120D)[colnames(BMW120D)=="BMW120DT2"] <- "Valeurs"

BMW120D <- BMW120D %>% pivot_wider(names_from = Catégories, values_from = Valeurs)
```

# Manip pour récupérer le nom du véhicule

```{r}
xpath <- as.character('//*[@id="Caractéristiques"]/div[4]/div[3]/p/a')

RajoutBMW120D <- urlzp %>%
  html_node(xpath = xpath) %>%
  html_text()

RajoutBMW120D <- as.data.frame(RajoutBMW120D)

RajoutBMW120D <- RajoutBMW120D %>%
  separate(col = "RajoutBMW120D",
           into = paste0("Info", 1:5), sep = " ") ## Séparer le df en plusieurs colonnes

RajoutBMW120D$Modèle <-paste(RajoutBMW120D$Info2,RajoutBMW120D$Info3,sep=" ") ## Rassembler les colonnes pour le modèle
RajoutBMW120D$Info2 <- NULL
RajoutBMW120D$Info3 <- NULL

RajoutBMW120D$Puissance <-paste(RajoutBMW120D$Info4,RajoutBMW120D$Info5,sep=" ") ## Rassembler les colonnes pour la puissance
RajoutBMW120D$Info4 <- NULL
RajoutBMW120D$Info5 <- NULL

base::colnames(RajoutBMW120D)[colnames(RajoutBMW120D)=="Info1"] <- "Marque"
```

# Manip pour récupérer le poids du véhicule

```{r}
xpath2 <- as.character('//*[@id="Caractéristiques"]/div[4]/text()[21]')

PoidsBMW120D <- urlzp %>%
  html_node(xpath = xpath2) %>%
  html_text()

PoidsBMW120D <- as.data.frame(PoidsBMW120D)

PoidsBMW120D <- PoidsBMW120D %>%
  separate(col = "PoidsBMW120D",
           into = paste0("Info", 1:2), sep = ":")

PoidsBMW120D <- PoidsBMW120D %>% pivot_wider(names_from = Info1, values_from = Info2)
```

