---
title: "Linear regression model"
author: "Valentin Henriot"
date: "5/25/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
```

```{r}
library(dplyr)
library(tidyr)
library(stats)
library(stargazer)
library(visreg)
```

```{r cars}
summary(mtcars)
```

```{r}
mtcars
```

```{r}
LinearReg <- lm(hp ~ qsec, data = mtcars)
```

```{r}
summary(LinearReg)
```

```{r}
plot(hp ~ qsec, data = mtcars, col=2)
abline(LinearReg,col=3,lwd=2)
bs <- round(coef(LinearReg), 3) 
lmlab <- paste0("hp = ", bs[1],
             ifelse(sign(bs[2])==1, " + ", " - "), abs(bs[2]), " qsec ")
mtext(lmlab, 3, line=-2)
```

```{r}
plot(hp~ qsec, data = mtcars)
abline(LinearReg,col=3,lwd=2) 
segments(mtcars$qsec,fitted(LinearReg), mtcars$qsec, mtcars$hp)
pred.frame<-data.frame(qsec=14:24) 
pc<-predict(LinearReg, interval="confidence", newdata=pred.frame)
pp<-predict(LinearReg, interval="prediction", newdata=pred.frame)
matlines(pred.frame, pc[,2:3], lty=c(2,2), col="blue") 
matlines(pred.frame, pp[,2:3], lty=c(3,3), col="red")
legend("topright",c("confiance","prediction"),lty=c(2,3) , col=c("blue","red"))
```

```{r}
MultipleLinearReg <- lm(qsec ~ hp + wt, data = mtcars)
```

```{r}
summary(MultipleLinearReg)
```

```{r eval=FALSE, include=FALSE}
stargazer(MultipleLinearReg, out="MultLinReg.htm")
```

```{r}
visreg2d(MultipleLinearReg, "wt", "hp", plot.type="image")
```

```{r}
visreg2d(MultipleLinearReg, "wt", "hp", plot.type="persp")
```

