---
title: "Titanic Competition"
author: "Valentin Henriot"
date: "6/30/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
```

```{r}
library(tidyverse)
library(ggplot2)
library(readr)
library(randomForest)
library(data.table)
library(caret)
```

# Download and reshape data

```{r}
train.data <- read_csv("~/Desktop/ProjectR/DataBase/trainTitanic.csv")
test.data <- read_csv("~/Desktop/ProjectR/DataBase/testTitanic.csv")
```

```{r}
train.data$Survived <- as.logical(train.data$Survived)
train.data$PassengerId <- as.character(train.data$PassengerId)
train.data$Pclass <- as.factor(train.data$Pclass)
train.data$Sex <- as.factor(train.data$Sex)
```

```{r}
summary(train.data)
```

# Basics ratios

```{r Men Survival Ratio}
ManSurvival <- filter(train.data, Sex == "male" & Survived == TRUE)
ManSurvivalCount <- nrow(ManSurvival)

ManTotal <- filter(train.data, Sex == "male")
ManTotalCount <- nrow(ManTotal)

RatioSurvivedMan <- ManSurvivalCount/ManTotalCount

print(paste("% of men who survived", RatioSurvivedMan))
```

```{r Women Survival Ratio}
WomanSurvival <- filter(train.data, Sex == "female" & Survived == TRUE)
WomanSurvivalCount <- nrow(WomanSurvival)

WomanTotal <- filter(train.data, Sex == "female")
WomanTotalCount <- nrow(WomanTotal)

RatioSurvivedWoman <- WomanSurvivalCount/WomanTotalCount

print(paste("% of women who survived", RatioSurvivedWoman))
```

```{r First class Survival Ratio}
FirstClassSurvival <- filter(train.data, Pclass == "1" & Survived == TRUE)
FirstClassSurvivalCount <- nrow(FirstClassSurvival)

FirstClassTotal <- filter(train.data, Pclass == "1")
FirstClassTotalCount <- nrow(FirstClassTotal)

RatioSurvivedFirstClass <- FirstClassSurvivalCount/FirstClassTotalCount

print(paste("% of 1st class passengers who survived", RatioSurvivedFirstClass))
```

```{r Second class Survival Ratio}
SecondClassSurvival <- filter(train.data, Pclass == "2" & Survived == TRUE)
SecondClassSurvivalCount <- nrow(SecondClassSurvival)

SecondClassTotal <- filter(train.data, Pclass == "2")
SecondClassTotalCount <- nrow(SecondClassTotal)

RatioSurvivedSecondClass <- SecondClassSurvivalCount/SecondClassTotalCount

print(paste("% of 2nd class passengers who survived", RatioSurvivedSecondClass))
```

```{r Third class Survival Ratio}
ThirdClassSurvival <- filter(train.data, Pclass == "3" & Survived == TRUE)
ThirdClassSurvivalCount <- nrow(ThirdClassSurvival)

ThirdClassTotal <- filter(train.data, Pclass == "3")
ThirdClassTotalCount <- nrow(ThirdClassTotal)

RatioSurvivedThirdClass <- ThirdClassSurvivalCount/ThirdClassTotalCount

print(paste("% of 3rd class passengers who survived", RatioSurvivedThirdClass))
```

```{r}
RatioSurvivedMan <- as.data.frame(RatioSurvivedMan)
RatioSurvivedWoman <- as.data.frame(RatioSurvivedWoman)
RatioSurvivedFirstClass <- as.data.frame(RatioSurvivedFirstClass)
RatioSurvivedSecondClass <- as.data.frame(RatioSurvivedSecondClass)
RatioSurvivedThirdClass <- as.data.frame(RatioSurvivedThirdClass)

RatioSurvived <- bind_cols(RatioSurvivedMan, RatioSurvivedWoman, RatioSurvivedFirstClass, RatioSurvivedSecondClass, RatioSurvivedThirdClass) %>% gather(key = "Category", value = "Value")

RatioSurvived$Category <- recode(RatioSurvived$Category, "RatioSurvivedMan" = "Man", "RatioSurvivedWoman" ="Woman", "RatioSurvivedFirstClass" = "First Class", "RatioSurvivedSecondClass" = "Second Class", "RatioSurvivedThirdClass" = "Third Class")
```

```{r}
ggplot(RatioSurvived) +
 aes(x = reorder(Category, -Value), fill = Value, weight = Value) +
 geom_bar() +
 scale_fill_viridis_c(option = "inferno") +
 labs(y = "Rate in %", title = "Survival Ratio by category") +
 ggthemes::theme_stata()
```

```{r}
sum(is.na(train.data$Age))
sum(is.na(train.data$Cabin))
```

### Faire des catégories d'âge

```{r}
train.data$Class.Age <- cut(train.data$Age, breaks = c(0, 5, 17, 30, 50, 81),include.lowest = TRUE)
```

### Faire une colonne avec Mr, Miss, etc

```{r}
train.data$Title <-
  ifelse(grepl("\\bMr\\b", train.data$Name, ignore.case = T),
         "Mr.",
         ifelse(
           grepl("\\bMrs\\b", train.data$Name, ignore.case = T),
           "Mrs.",
           ifelse(
             grepl("Miss.", train.data$Name, ignore.case = T),
             "Miss.",
             ifelse(
               grepl("Master.", train.data$Name, ignore.case = T),
               "Master.",
               ifelse(
                 grepl("Don.", train.data$Name, ignore.case = T),
                 "Don.",
                 ifelse(
                   grepl("Rev.", train.data$Name, ignore.case = T),
                   "Rev.",
                   ifelse(
                     grepl("Dr.", train.data$Name, ignore.case = T),
                     "Dr.",
                     ifelse(
                       grepl("Mme.", train.data$Name, ignore.case = T),
                       "Mme.",
                       ifelse(
                         grepl("Ms.", train.data$Name, ignore.case = T),
                         "Ms.",
                         ifelse(
                           grepl("Major.", train.data$Name, ignore.case = T),
                           "Major",
                           ifelse(
                             grepl("Mlle.", train.data$Name, ignore.case = T),
                             "Mlle",
                             ifelse(
                               grepl("Col.", train.data$Name, ignore.case = T),
                               "Col.",
                               ifelse(
                                 grepl("Capt.", train.data$Name, ignore.case = T),
                                 "Capt.",
                                 ifelse(
                                   grepl("Countess.", train.data$Name, ignore.case = T),
                                   "Countess.",
                                   "Unknown"
                                 )
                               )
                             )
                           )
                         )
                       )
                     )
                   )
                 )
               )
             )
           )
         ))
```


```{r Survival by title}
Mr <- filter(train.data, Title == "Mr." & Survived == T) %>% nrow() / filter(train.data, Title == "Mr.") %>% nrow()
Mr <- as.data.frame(Mr)

Mrs <- filter(train.data, Title == "Mrs." & Survived == T) %>% nrow() / filter(train.data, Title == "Mrs.") %>% nrow()
Mrs <- as.data.frame(Mrs)

Miss <- filter(train.data, Title == "Miss." & Survived == T) %>% nrow() / filter(train.data, Title == "Miss.") %>% nrow()
Miss <- as.data.frame(Miss)

Master <- filter(train.data, Title == "Master." & Survived == T) %>% nrow() / filter(train.data, Title == "Master.") %>% nrow()
Master <- as.data.frame(Master)

Don <- filter(train.data, Title == "Don." & Survived == T) %>% nrow() / filter(train.data, Title == "Don.") %>% nrow()
Don <- as.data.frame(Don)

Rev <- filter(train.data, Title == "Rev." & Survived == T) %>% nrow() / filter(train.data, Title == "Rev.") %>% nrow()
Rev <- as.data.frame(Rev)

Dr <- filter(train.data, Title == "Dr." & Survived == T) %>% nrow() / filter(train.data, Title == "Dr.") %>% nrow()
Dr <- as.data.frame(Dr)

Mme <- filter(train.data, Title == "Mme." & Survived == T) %>% nrow() / filter(train.data, Title == "Mme.") %>% nrow()
Mme <- as.data.frame(Mme)

Ms <- filter(train.data, Title == "Ms." & Survived == T) %>% nrow() / filter(train.data, Title == "Ms.") %>% nrow()
Ms <- as.data.frame(Ms)

Major <- filter(train.data, Title == "Major" & Survived == T) %>% nrow() / filter(train.data, Title == "Major") %>% nrow()
Major <- as.data.frame(Major)

Mlle <- filter(train.data, Title == "Mlle" & Survived == T) %>% nrow() / filter(train.data, Title == "Mlle") %>% nrow()
Mlle <- as.data.frame(Mlle)

Col <- filter(train.data, Title == "Col." & Survived == T) %>% nrow() / filter(train.data, Title == "Col.") %>% nrow()
Col <- as.data.frame(Col)

Capt <- filter(train.data, Title == "Capt." & Survived == T) %>% nrow() / filter(train.data, Title == "Capt.") %>% nrow()
Capt <- as.data.frame(Capt)

Countess <- filter(train.data, Title == "Countess." & Survived == T) %>% nrow() / filter(train.data, Title == "Countess.") %>% nrow()
Countess <- as.data.frame(Countess)

TitleSurvival <- bind_cols(Mr, Mrs, Miss, Master, Don, Rev, Dr, Mme, Ms, Major, Mlle, Col, Capt, Countess) %>% gather(key = "Category", value = "Value")
```

```{r}
ggplot(TitleSurvival) +
 aes(x = reorder(Category, -Value), fill = Value, weight = Value) +
 geom_bar() +
 scale_fill_viridis_c(option = "inferno") +
 labs(y = "Rate in %", title = "Survival Ratio by title") +
 ggthemes::theme_stata()
```

```{r Survival by Class Age}
Kids <- filter(train.data, Class.Age == "[0,5]" & Survived == TRUE) %>% nrow() / filter(train.data, Class.Age == "[0,5]") %>% nrow()
Kids <- as.data.frame(Kids)

Teenagers <- filter(train.data, Class.Age == "(5,17]" & Survived == TRUE) %>% nrow() / filter(train.data, Class.Age == "(5,17]") %>% nrow()
Teenagers <- as.data.frame(Teenagers)

YoungAdults <- filter(train.data, Class.Age == "(17,30]" & Survived == TRUE) %>% nrow() / filter(train.data, Class.Age == "(17,30]") %>% nrow()
YoungAdults <- as.data.frame(YoungAdults)

Adults <- filter(train.data, Class.Age == "(30,50]" & Survived == TRUE) %>% nrow() / filter(train.data, Class.Age == "(30,50]") %>% nrow()
Adults <- as.data.frame(Adults)

Seniors <- filter(train.data, Class.Age == "(50,81]" & Survived == TRUE) %>% nrow() / filter(train.data, Class.Age == "(50,81]") %>% nrow()
Seniors <- as.data.frame(Seniors)

ClassAgeSurvival <- bind_cols(Kids, Teenagers, YoungAdults, Adults, Seniors) %>% gather(key = "Category", value = "Value")
```

```{r}
ggplot(ClassAgeSurvival) +
 aes(x = reorder(Category, -Value), fill = Value, weight = Value) +
 geom_bar() +
 scale_fill_viridis_c(option = "inferno") +
 labs(y = "Rate in %", title = "Survival Ratio by age class") +
 ggthemes::theme_stata()
```

# Random Forest

### Remplacer les NAs par les valeurs médianes (Age)

```{r Préparation modele}
train.data2 <- data.table(train.data)
setkey(train.data2, Title)

train.data2[,Age := ifelse(is.na(Age), median(Age, na.rm=TRUE), Age), by=Title] # ré-organiser en fonction du titre

train.data2$PassengerId <- as.numeric(train.data2$PassengerId)

train.data2 <- train.data2[order(train.data2$PassengerId),]
#train.data2$PassengerId <- as.character(train.data2$PassengerId)
```

```{r Classe d'age et de prix}
train.data2$Class.Age <- cut(train.data2$Age, breaks = c(0, 5, 17, 30, 50, 81),include.lowest = TRUE)
train.data2$Class.Fare <- cut(train.data2$Fare, breaks = c(0, 8, 15, 33, 50, 100, 513), include.lowest = TRUE)
```

```{r Suppression colonnes inutiles}
train.data2 <- train.data2[,-11] # retirer colonne cabine (pas d'intérêt, trop de valeurs manquantes)
#train.data2 <- train.data2[,-1] # retirer colonne ID passager
train.data2 <- train.data2[,-4] # retirer colonne Name
train.data2 <- train.data2[,-8] # retirer colonne Ticket (pas d'intérêt, toutes les valeurs sont différentes)
train.data2 <- train.data2[,-5] # retirer colonne Age (conserve uniquement Class.Age)
train.data2 <- train.data2[,-7] # retirer colonne Fare (conserve uniquement Class.Fare)

train.data2$Embarked <- as.factor(train.data2$Embarked)
train.data2$Title <- as.factor(train.data2$Title)
train.data2$Survived <- as.factor(train.data2$Survived)
```

### Deux valeurs manquantes pour train.data2 variable "Embarked"

```{r}
train.data2$Embarked <- train.data2[train.data2$Embarked == "","Embarked"] <- "S" ## Remplacement par la valeur la plus commune
```

## Plus pertinent

```{r}
set.seed(4321)
train.titanic <- train.data2 %>% sample_frac(0.8)
test.titanic <- anti_join(train.data2, train.titanic)

set.seed(4321)
(model <- randomForest(Survived~., data = train.titanic, ntree = 1000, na.action = na.roughfix))
```

```{r}
model$importance
```

```{r}
varImpPlot(model)
```

### Plus pertinent

```{r}
test.titanic$predicted <- predict(model, test.titanic)

table(test.titanic$predicted, test.titanic$Survived)
```

```{r}
conf <- confusionMatrix(data = test.titanic$predicted, reference = test.titanic$Survived)
```

# Appliquer le modèle au jeu de données test

```{r}
test.data$Pclass <- as.factor(test.data$Pclass)
test.data$Sex <- as.factor(test.data$Sex)
```

```{r}
test.data$Title <-
  ifelse(grepl("\\bMr\\b", test.data$Name, ignore.case = T),
         "Mr.",
         ifelse(
           grepl("\\bMrs\\b", test.data$Name, ignore.case = T),
           "Mrs.",
           ifelse(
             grepl("Miss.", test.data$Name, ignore.case = T),
             "Miss.",
             ifelse(
               grepl("Master.", test.data$Name, ignore.case = T),
               "Master.",
               ifelse(
                 grepl("Don.", test.data$Name, ignore.case = T),
                 "Don.",
                 ifelse(
                   grepl("Rev.", test.data$Name, ignore.case = T),
                   "Rev.",
                   ifelse(
                     grepl("Dr.", test.data$Name, ignore.case = T),
                     "Dr.",
                     ifelse(
                       grepl("Mme.", test.data$Name, ignore.case = T),
                       "Mme.",
                       ifelse(
                         grepl("Ms.", test.data$Name, ignore.case = T),
                         "Ms.",
                         ifelse(
                           grepl("Major.", test.data$Name, ignore.case = T),
                           "Major",
                           ifelse(
                             grepl("Mlle.", test.data$Name, ignore.case = T),
                             "Mlle",
                             ifelse(
                               grepl("Col.", test.data$Name, ignore.case = T),
                               "Col.",
                               ifelse(
                                 grepl("Capt.", test.data$Name, ignore.case = T),
                                 "Capt.",
                                 ifelse(
                                   grepl("Countess.", test.data$Name, ignore.case = T),
                                   "Countess.",
                                   "Unknown"
                                 )
                               )
                             )
                           )
                         )
                       )
                     )
                   )
                 )
               )
             )
           )
         ))
```

```{r}
test.data2 <- data.table(test.data)
setkey(test.data2, Title)

test.data2[,Age := ifelse(is.na(Age), median(Age, na.rm=TRUE), Age), by=Title]
test.data2[,Fare := ifelse(is.na(Fare), median(Fare, na.rm=TRUE), Fare), by=Title]

test.data2 <- test.data2[order(test.data2$PassengerId),]
```

```{r}
test.data2$Class.Age <- cut(test.data2$Age, breaks = c(0, 5, 17, 30, 50, 81),include.lowest = TRUE)
test.data2$Class.Fare <- cut(test.data2$Fare, breaks = c(0, 8, 15, 33, 50, 100, 513), include.lowest = TRUE)
```

```{r}
test.data2 <- test.data2[,-10] # retirer colonne cabine (pas d'intérêt, trop de valeurs manquantes)
test.data2 <- test.data2[,-3] # retirer colonne Name
test.data2 <- test.data2[,-7] # retirer colonne Ticket (pas d'intérêt, toutes les valeurs sont différentes)
test.data2 <- test.data2[,-4] # retirer colonne Age (conserve uniquement Class.Age)
test.data2 <- test.data2[,-6] # retirer colonne Fare (conserve uniquement Class.Fare)

test.data2$Embarked <- as.factor(test.data2$Embarked)
test.data2$Title <- as.factor(test.data2$Title)
test.data2$Survived <- NA
```

## Nouvelle manip

```{r}
train.titanic <- train.data2
test.titanic <- test.data2

train.titanic$dftest <- TRUE
test.titanic$dftest <- FALSE
fulldf.titanic <- rbind(train.titanic, test.titanic)
```

```{r}
train.titanic <- fulldf.titanic[fulldf.titanic$dftest == TRUE,]
test.titanic <- fulldf.titanic[fulldf.titanic$dftest == FALSE,]
```

```{r}
survived.equation <- "Survived ~ Pclass + Sex + Class.Age + SibSp + Parch + Class.Fare + Embarked + Title"
survived.formula <- as.formula(survived.equation)

set.seed(4321)
model <- randomForest(formula=survived.formula, data = train.titanic, ntree = 1000, na.action = na.roughfix)
```


```{r}
test.titanic$Survived <- predict(model, newdata = test.titanic)
```

